name: 'Unified Deployment System'
description: 'A comprehensive deployment system with SSL, dynamic routing, and plugin support'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  command:
    description: 'Command to run (deploy, setup, cleanup)'
    required: true
    default: 'deploy'
  app-name:
    description: 'Application name'
    required: true
  image:
    description: 'Docker image name (can be a comma-separated list for multiple services)'
    required: false
  tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'
  domain:
    description: 'Domain name for deployment'
    required: true
  route-type:
    description: 'Type of route (path or subdomain)'
    required: false
    default: 'path'
  route:
    description: 'Route path or subdomain prefix'
    required: false
  port:
    description: 'Internal container port to expose'
    required: false
    default: '3000'
  ssl:
    description: 'Enable SSL'
    required: false
    default: 'true'
  ssl-email:
    description: 'Email for SSL certificate registration'
    required: false
  volumes:
    description: 'Volume mappings (comma-separated list of source:target)'
    required: false
  env-vars:
    description: 'Environment variables (JSON string)'
    required: false
  persistent:
    description: 'Mark services as persistent (not updated during deployments)'
    required: false
    default: 'false'
  compose-file:
    description: 'Path to custom docker-compose.yml file'
    required: false
  use-profiles:
    description: 'Use Docker Compose profiles'
    required: false
    default: 'true'
  extra-hosts:
    description: 'Extra hosts to add to containers (comma-separated list of host:ip)'
    required: false
  health-check:
    description: 'Health check endpoint'
    required: false
    default: '/health'
  health-check-type:
    description: 'Health check type (http, tcp, container, command)'
    required: false
    default: 'auto'
  health-check-command:
    description: 'Custom command for health check when using command type'
    required: false
  port-auto-assign:
    description: 'Automatically assign ports if the specified port is in use'
    required: false
    default: 'true'
  version-tracking:
    description: 'Enable version tracking'
    required: false
    default: 'true'
  pg-migration-enabled:
    description: 'Enable PostgreSQL migrations'
    required: false
    default: 'false'
  pg-connection-string:
    description: 'PostgreSQL connection string'
    required: false
  pg-backup-enabled:
    description: 'Enable PostgreSQL backups before migrations'
    required: false
    default: 'true'
  pg-migration-script:
    description: 'Custom PostgreSQL migration script'
    required: false
  telegram-enabled:
    description: 'Enable Telegram notifications'
    required: false
    default: 'false'
  telegram-bot-token:
    description: 'Telegram bot token'
    required: false
  telegram-chat-id:
    description: 'Telegram chat ID'
    required: false
  telegram-notify-level:
    description: 'Minimum level for Telegram notifications (debug, info, warning, error)'
    required: false
    default: 'info'
  telegram-include-logs:
    description: 'Include logs in Telegram notifications'
    required: false
    default: 'true'
  max-log-lines:
    description: 'Maximum number of log lines to collect on error'
    required: false
  working-dir:
    description: 'Working directory on the remote server'
    required: false
    default: '/opt/uds'
  host:
    description: 'Remote host'
    required: true
  username:
    description: 'Remote username'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create configuration file
      shell: bash
      run: |
        echo "Creating deployment configuration..."
        # Format JSON configuration from inputs
        cat > ${{ github.action_path }}/config.json << EOF
        {
          "command": "${{ inputs.command }}",
          "app_name": "${{ inputs.app-name }}",
          "image": "${{ inputs.image }}",
          "tag": "${{ inputs.tag }}",
          "domain": "${{ inputs.domain }}",
          "route_type": "${{ inputs.route-type }}",
          "route": "${{ inputs.route }}",
          "port": "${{ inputs.port }}",
          "ssl": ${{ inputs.ssl == 'true' }},
          "ssl_email": "${{ inputs.ssl-email }}",
          "volumes": "${{ inputs.volumes }}",
          "env_vars": ${{ inputs.env-vars || '{}' }},
          "persistent": ${{ inputs.persistent == 'true' }},
          "compose_file": "${{ inputs.compose-file }}",
          "use_profiles": ${{ inputs.use-profiles == 'true' }},
          "extra_hosts": "${{ inputs.extra-hosts }}",
          "health_check": "${{ inputs.health-check }}",
          "health_check_timeout": ${{ inputs.health-check-timeout || '60' }},
          "health_check_type": "${{ inputs.health-check-type }}",
          "health_check_command": "${{ inputs.health-check-command }}",
          "port_auto_assign": ${{ inputs.port-auto-assign == 'true' }},
          "version_tracking": ${{ inputs.version-tracking == 'true' }},
          "pg_migration_enabled": ${{ inputs.pg-migration-enabled == 'true' }},
          "pg_connection_string": "${{ inputs.pg-connection-string }}",
          "pg_backup_enabled": ${{ inputs.pg-backup-enabled == 'true' }},
          "pg_migration_script": "${{ inputs.pg-migration-script }}",
          "telegram_enabled": ${{ inputs.telegram-enabled == 'true' }},
          "telegram_bot_token": "${{ inputs.telegram-bot-token }}",
          "telegram_chat_id": "${{ inputs.telegram-chat-id }}",
          "telegram_notify_level": "${{ inputs.telegram-notify-level }}",
          "telegram_include_logs": ${{ inputs.telegram-include-logs == 'true' }},
          "max_log_lines": ${{ inputs.max-log-lines || '100' }},
          "plugins": "${{ inputs.plugins }}",
          "auto_install_deps": true
        }
        EOF

    - name: Run deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        script_stop: true
        script: |
          set -e
          
          echo "Setting up deployment environment..."
          # Create working directory and app directory
          WORKING_DIR="${{ inputs.working-dir }}"
          mkdir -p "$WORKING_DIR/${{ inputs.app-name }}"
          cd "$WORKING_DIR"
          
          # Create setup script function
          cat > ./setup_uds.sh << 'EOL'
          #!/bin/bash
          
          # Function to install UDS
          setup_uds() {
            local uds_repo="https://${GIT_TOKEN}@github.com/elijahmont3x/unified-deploy-action.git"
            local uds_version="master" # TODO: Make this configurable
            local target_dir="$1"
            
            # Create target directory if it doesn't exist
            mkdir -p "$target_dir"
            
            if [ ! -f "$target_dir/uds-core.sh" ]; then
              echo "Installing Unified Deployment System..."
              
              # Create temporary directory
              local temp_dir=$(mktemp -d)
              
              # Clone repository
              if ! git clone --branch "$uds_version" "$uds_repo" "$temp_dir"; then
                echo "Failed to clone UDS repository"
                rm -rf "$temp_dir"
                return 1
              fi
              
              # Copy files
              cp -r "$temp_dir/scripts/"* "$target_dir/"
              mkdir -p "$target_dir/plugins"
              cp -r "$temp_dir/plugins/"* "$target_dir/plugins/"
              
              # Clean up
              rm -rf "$temp_dir"
              
              # Make scripts executable
              chmod +x "$target_dir"/*.sh
              
              echo "UDS installed successfully"
              return 0
            else
              echo "UDS is already installed"
              return 0
            fi
          }
          
          # Run the setup function
          setup_uds "$1"
          EOL
          
          # Make script executable
          chmod +x ./setup_uds.sh
          
          # Install UDS
          ./setup_uds.sh "$WORKING_DIR"
          
          # Copy config file
          cat > ${{ inputs.app-name }}-config.json << 'EOF'
          ${{ github.action_path }}/config.json
          EOF
          
          # Run the appropriate command
          echo "Running ${{ inputs.command }} command..."
          if [ "${{ inputs.command }}" == "setup" ]; then
            ./uds-setup.sh --config ${{ inputs.app-name }}-config.json
          elif [ "${{ inputs.command }}" == "cleanup" ]; then
            ./uds-cleanup.sh --config ${{ inputs.app-name }}-config.json
          else
            # Default is deploy
            ./uds-deploy.sh --config ${{ inputs.app-name }}-config.json
          fi